version: '3'

services:
  
  spread_sweat_api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    command: ${SPREAD_SWEAT_CUSTOM_BOOT_CMD:-npm run up}
    restart: always
    env_file:
      - ".env"
    ports:
      - "${VITE_API_PORT}:${VITE_API_PORT}"
    volumes:
      - ./api:/app
      - /app/node_modules 

  spread_sweat_ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    command: ${SPREAD_SWEAT_CUSTOM_BOOT_CMD:-npm run up}
    restart: always
    env_file:
      - ".env"
    ports:
      - "${VITE_UI_PORT}:${VITE_UI_PORT}"
    volumes:
      - ./ui:/app
      - /app/node_modules
        
